apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingmanagement
  labels:
    app: bookingmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookingmanagement
  template:
    metadata:
      labels:
        app: bookingmanagement
    spec:
      containers:
        - name: bookingmanagement
          image: adarsh1417/sports-arena:bookingmanagement
          imagePullPolicy: Always
          ports:
            - containerPort: 8087

---
apiVersion: v1
kind: Service
metadata:
  name: bookingmanagement
spec:
  ports:
    - targetPort: 8087
      port: 8087
  selector:
    app: bookingmanagement
  type: NodePort