---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
  clusterIP: None
  selector:
    app: mongodb
...
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb
  name: mongodbsts
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: mongo:latest
          name: mongodb
          ports:
            - containerPort: 27017
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'Password@123'
            - name: MYSQL_PASSWORD
              value: 'root'
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: 'yes'