apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatservice
  labels:
    app: chatservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatservice
  template:
    metadata:
      labels:
        app: chatservice
    spec:
      containers:
        - name: chat-service
          image: adarsh1417/sports-arena:chatservice
          imagePullPolicy: Always
          ports:
            - containerPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: chatservice
spec:
  ports:
    - targetPort: 8086
      port: 8086
  selector:
    app: chatservice
  type: LoadBalancer