apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamup
  labels:
    app: teamup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamup
  template:
    metadata:
      labels:
        app: teamup
    spec:
      containers:
        - name: teamup
          image: adarsh1417/sports-arena:teamup
          imagePullPolicy: Always
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: teamup
spec:
  ports:
    - targetPort: 8082
      port: 8082
  selector:
    app: teamup
  type: NodePort