apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-webapp
  labels:
    app: product-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-webapp
  template:
    metadata:
      labels:
        app: product-webapp
    spec:
      containers:
        - name: product-webapp
          image: adarsh1417/sports-arena:product-webapp
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: product-webapp
spec:
  ports:
    - targetPort: 3000
      port: 80
  selector:
    app: product-webapp
  type: NodePort