eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://34.201.191.117:8761/eureka

server:
  port: 8081
spring:
  application:
    name: user-service
  data:
    mongodb:
      database: players
      host: 34.201.191.117
      port: 27017
  datasource:
    driver-name: mongodb.jdbc.MongoDriver

  rabbitmq:
    port: 5672
    host: 34.201.191.117
    username: guest
    password: guest



# spring:
#   application:
#     name: user-service
#   cloud:
#     config:
#       uri: http://localhost:8888
#       import-check:
#         enabled: false
# management:
#   security:
#     enabled: false
