server:
  port: 8087
spring:
  data:
    mongodb:
      host: 34.201.191.117
      port: 27017
      database: Bookings
  application:
    name: bookings-management

  rabbitmq:
    port: 5672
    host: 34.201.191.117
    username: guest
    password: guest
    
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka



# server:
#   port: 8087
# spring:
#   data:
#     mongodb:
#       host: localhost
#       port: 27017
#       database: Bookings
#   application:
#     name: bookings-management
#   cloud:
#     config:
#       uri: http://localhost:8888
#       import-check.enabled: false
# management:
#   security:
#     enabled: false
