server:
  port: 8082
  
spring:
  application:
    name: team-up
  data:
    mongodb:
      host: localhost
      port: 27017
      database: TeamupDB

  rabbitmq:
    port: 5672
    host: 34.201.191.117
    username: guest
    password: guest

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://34.201.191.117:8761/eureka

# spring:
#   application:
#     name: team-up
#   cloud:
#     config:
#       uri: http://localhost:8888
#       import-check:
#         enabled: false
#     mangement:
#       security:
#         enabled: false
